//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NX_QScript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NX_QScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x3140d22e &quot;b_nodoubt_lose_depressed&quot;
        ///0xd9632956 &quot;g_nodoubt_lose_depressed&quot;
        ///0xac0dfc28 &quot;scripts/av_presets/jow_rainbowroad.qb&quot;
        ///0xe90b86a8 &quot;JOW_RainbowRoad&quot;
        ///0x6c8c7d45 &quot;scripts/av_presets/og_band_moment_b.qb&quot;
        ///0x6364dfe8 &quot;OG_Band_Moment_B&quot;
        ///0xd4301a20 &quot;scripts/av_presets/og_band_moment_c.qb&quot;
        ///0x1463ef7e &quot;OG_Band_Moment_C&quot;
        ///0x49e72299 &quot;scripts/av_presets/og_band_moment_d.qb&quot;
        ///0x8a077add &quot;OG_Band_Moment_D&quot;
        ///0xe3eeea12 &quot;scripts/av_presets/og_band_moment_f.qb&quot;
        ///0x64091bf1 &quot;OG_Band_Moment_F&quot;
        ///0x5b528d77 &quot;scri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QBKeysBank {
            get {
                return ResourceManager.GetString("QBKeysBank", resourceCulture);
            }
        }
    }
}
